### ISSUE TITLE
Transaction test error when installing .rpm using yum

### ISSUE THREAD

**Issue by marcomeyerVFX** [grosjo/tomboy-reborn#2]
I am getting this error when installing using yum

```
Error: Transaction test error:
  file / from install of tomboy-reborn-1.0.0-2.x86_64 conflicts with file from package filesystem-3.8-2.el8.x86_64
  file /usr/bin from install of tomboy-reborn-1.0.0-2.x86_64 conflicts with file from package filesystem-3.8-2.el8.x86_64
```

I've seen this in the past, the installer is trying to create these root directories which should normally exist on every system.
Usually I would remove the responsible lines from the SPEC file but no idea how your rpm packages are generated.

Cheers.

**Comment by grosjo** [comment]
Please kidnly try again with https://github.com/grosjo/tomboy-reborn/releases/download/1.0.0/tomboy-reborn-1.0.0-1.x86_64.rpm

**Comment by marcomeyerVFX** [comment]
Fixed, thanks!
